print('lambda30'.isalnum())
print('lambda'.isalnum())
print('30'.isalnum())
print('@'.isalnum())
print('lambda_30'.isalnum())
print(''.isalnum())
print("Eta".find("ta"))
print("Eta".find("mma"))
print("Moooo".islower())
print('moooo'.islower())
print(' \n '.isspace())
print(" ".isspace())
print("mooo mooo mooo".isspace())
print("Moooo".isupper())
print('moooo'.isupper())
print('MOOOO'.isupper())
print(",".join(["omicron", "pi", "rho"]))
print("SiGmA=60".lower())
print("www.netacad.com".replace("netacad.com", "pythoninstitute.org"))
print("This is it!".replace("is", "are"))
print("Apple juice".replace("juice", ""))

