print('lambda30'.isalnum())
print('lambda'.isalnum())
print('30'.isalnum())
print('@'.isalnum())
print('lambda_30'.isalnum())
print(''.isalnum())
print("Eta".find("ta"))
print("Eta".find("mma"))
print("Moooo".islower())
print('moooo'.islower())
print(' \n '.isspace())
print(" ".isspace())
print("mooo mooo mooo".isspace())
print("Moooo".isupper())
print('moooo'.isupper())
print('MOOOO'.isupper())

